name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Ruff (non-blocking)
        run: ruff check . || true
      - name: Black (non-blocking)
        run: black --check . || true
      - name: Mypy (non-blocking)
        run: mypy . || true
      - name: Tests
        run: pytest -q